// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11016bm3ey5EgTSTVVBz8PbVVVJ3J3N0',
    appId: '1:238354943592:web:227ae38169f8706e53f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    authDomain: 'logbook-auth-dev.firebaseapp.com',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
    measurementId: 'G-QE73TN52WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHc8SlhoG9KcIq356CwJ3D2nLP-78kQk',
    appId: '1:34296706111:android:885f3976d853be9eebf48a',
    messagingSenderId: '34296706111',
    projectId: 'logbook-b19ed',
    storageBucket: 'logbook-b19ed.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1sAEN7GS33LcsiOVUC5b3npgq6lxC--k',
    appId: '1:34296706111:ios:0c855c2dc50b42d9ebf48a',
    messagingSenderId: '34296706111',
    projectId: 'logbook-b19ed',
    storageBucket: 'logbook-b19ed.firebasestorage.app',
    androidClientId: '34296706111-cmo7686vs6gt4bj4qrkmrp25lgcdn9r5.apps.googleusercontent.com',
    iosClientId: '34296706111-0ann0c13688t1t2pbrodoc4tojs7f2co.apps.googleusercontent.com',
    iosBundleId: 'com.ziegler.logbook',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1sAEN7GS33LcsiOVUC5b3npgq6lxC--k',
    appId: '1:34296706111:ios:0c855c2dc50b42d9ebf48a',
    messagingSenderId: '34296706111',
    projectId: 'logbook-b19ed',
    storageBucket: 'logbook-b19ed.firebasestorage.app',
    androidClientId: '34296706111-cmo7686vs6gt4bj4qrkmrp25lgcdn9r5.apps.googleusercontent.com',
    iosClientId: '34296706111-0ann0c13688t1t2pbrodoc4tojs7f2co.apps.googleusercontent.com',
    iosBundleId: 'com.ziegler.logbook',
  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA11016bm3ey5EgTSTVVBz8PbVVVJ3J3N0',
    appId: '1:238354943592:web:d250d2d216a1b81453f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    authDomain: 'logbook-auth-dev.firebaseapp.com',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
    measurementId: 'G-HRQF5ZRD5X',
  );
}
