// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA11016bm3ey5EgTSTVVBz8PbVVVJ3J3N0',
    appId: '1:238354943592:web:227ae38169f8706e53f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    authDomain: 'logbook-auth-dev.firebaseapp.com',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
    measurementId: 'G-QE73TN52WL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI7MFrpYIkdpG_x6-pealt3IHFNBcm-bQ',
    appId: '1:238354943592:android:17d48f0ed9549c2553f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR52cSkytVtjhLeuCNvzHphhCQVDIMkic',
    appId: '1:238354943592:ios:bb7b2307cddb2a8353f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
    iosBundleId: 'com.ziegler.logbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR52cSkytVtjhLeuCNvzHphhCQVDIMkic',
    appId: '1:238354943592:ios:bb7b2307cddb2a8353f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
    iosBundleId: 'com.ziegler.logbook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA11016bm3ey5EgTSTVVBz8PbVVVJ3J3N0',
    appId: '1:238354943592:web:d250d2d216a1b81453f5dd',
    messagingSenderId: '238354943592',
    projectId: 'logbook-auth-dev',
    authDomain: 'logbook-auth-dev.firebaseapp.com',
    storageBucket: 'logbook-auth-dev.firebasestorage.app',
    measurementId: 'G-HRQF5ZRD5X',
  );
}
